# Generated by Django 5.0.6 on 2025-08-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='technician_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
