# Generated by Django 5.0.6 on 2025-08-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stock',
        ),
    ]
