# Generated by Django 5.0.6 on 2025-08-05 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0002_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_from', to='enterprise.person'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_to', to='enterprise.person'),
        ),
        migrations.AddField(
            model_name='credit',
            name='transaction',
            field=models.ManyToManyField(blank=True, related_name='credit_transactions', to='transactions.transaction'),
        ),
    ]
